---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files: 
  - ../bluemix-vars.yaml

  tasks:

  - name: create instance
    wascloud_instance:
      state: present
      name: "{{ was_instance_name }}"
      instance_type: WASBase
      size: s
      software_level: 8.5.5
      region: "{{ region }}"
      org: "{{ org }}"
      space: "{{ space }}"
      apikey: "{{ apikey }}"
      wait: False
    register: was_instance
