---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files: 
  - ../bluemix-vars.yaml

  tasks:

  - name: create instance
    wascloud_instance:
      state: latest
      name: "{{ was_instance_name }}"
      instance_type: WASBase
      size: s
      region: "{{ region }}"
      org: "{{ org }}"
      space: "{{ space }}"
      apikey: "{{ apikey }}"
      public_ip: true
    register: was_instance
